.386
.MODEL FLAT, STDCALL

GetStdHandle PROTO STDCALL :DWORD

GetNumberOfConsoleInputEvents PROTO STDCALL :DWORD,:DWORD
	;_In_  HANDLE  hConsoleInput,
	;_Out_ LPDWORD lpcNumberOfEvents

WriteConsoleA PROTO STDCALL :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
	;_In_             HANDLE  hConsoleOutput,
	;_In_       const VOID    *lpBuffer,
	;_In_             DWORD   nNumberOfCharsToWrite,
	;_Out_opt_        LPDWORD lpNumberOfCharsWritten,
	;_Reserved_       LPVOID  lpReserved

ReadConsoleInputA PROTO STDCALL :DWORD,:DWORD,:DWORD,:DWORD
	;_In_  HANDLE        hConsoleInput,
	;_Out_ PINPUT_RECORD lpBuffer,
	;_In_  DWORD         nLength,
	;_Out_ LPDWORD       lpNumberOfEventsRead

SetConsoleMode PROTO STDCALL :DWORD,:DWORD
	;_In_ HANDLE hConsoleHandle,
	;_In_ DWORD  dwMode

.DATA
	NOMEMORYLEAKORELSE DWORD ?
	HANDLEIN DWORD ?
	HANDLEOUT DWORD ?
	MSG BYTE 1BH, "[48;5;33m", 1BH, "]0;ConsoleTest", 07H, "Hello World from EXE!", 0
	MSGLEN DWORD 48
	BUFFER BYTE 64 DUP(?)

.CODE
START PROC
	;GET HANDLES
	PUSH -10
	CALL GetStdHandle
	MOV HANDLEIN, EAX

	PUSH -11
	CALL GetStdHandle
	MOV HANDLEOUT, EAX

	MOV EAX, 05H
	PUSH EAX
	PUSH HANDLEOUT
	CALL SetConsoleMode

	;WRITE MSG
	LEA EAX, [MSG]
	LEA EDX, [NOMEMORYLEAKORELSE]
	PUSH 0
	PUSH EDX
	PUSH MSGLEN
	PUSH EAX
	PUSH HANDLEOUT
	CALL WriteConsoleA
	JMP WAITKEY

START ENDP

WAITKEY PROC
	;CHECK EVENTS
	LEA EAX, [NOMEMORYLEAKORELSE]
	PUSH EAX
	PUSH HANDLEIN
	CALL GetNumberOfConsoleInputEvents
	MOV EAX, NOMEMORYLEAKORELSE
	CMP EAX, 00H
	JE WAITKEY

	;READ EVENTS
	LEA EBX, [BUFFER]
	LEA EAX, [NOMEMORYLEAKORELSE]
	PUSH EAX
	PUSH 1
	PUSH EBX
	PUSH HANDLEIN
	CALL ReadConsoleInputA

	;SANITY CHECK
	CMP EAX, 00H
	JE WAITKEY

	;CHECK IF KEYBOARD EVENT
	MOV AL, BUFFER
	CMP AL, 01H ;KEY_EVENT_RECORD
	JE ENDING
	JMP WAITKEY
ENDING:
	RET
WAITKEY ENDP
END