.386
.MODEL FLAT, STDCALL

GetStdHandle PROTO STDCALL :DWORD

GetNumberOfConsoleInputEvents PROTO STDCALL :DWORD,:DWORD
	;_In_  HANDLE  hConsoleInput,
	;_Out_ LPDWORD lpcNumberOfEvents

WriteConsoleA PROTO STDCALL :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
	;_In_             HANDLE  hConsoleOutput,
	;_In_       const VOID    *lpBuffer,
	;_In_             DWORD   nNumberOfCharsToWrite,
	;_Out_opt_        LPDWORD lpNumberOfCharsWritten,
	;_Reserved_       LPVOID  lpReserved

ReadConsoleInputA PROTO STDCALL :DWORD,:DWORD,:DWORD,:DWORD
	;_In_  HANDLE        hConsoleInput,
	;_Out_ PINPUT_RECORD lpBuffer,
	;_In_  DWORD         nLength,
	;_Out_ LPDWORD       lpNumberOfEventsRead

SetConsoleMode PROTO STDCALL :DWORD,:DWORD
	;_In_ HANDLE hConsoleHandle,
	;_In_ DWORD  dwMode

.DATA
	NOMEMORYLEAKORELSE DWORD ?
	HANDLEIN DWORD ?
	HANDLEOUT DWORD ?
	ACTUALCOLORBYTE BYTE 0
	MSG BYTE 1BH, "[H", 1BH, "[48;5;"
	COLORBYTE BYTE "0033"
	MSGEND BYTE "m", 1BH, "]0;ConsoleTest", 07H, "Hello World from EXE!", 0
	MSGLEN DWORD 53
	BUFFER BYTE 64 DUP(?)

.CODE
START PROC
	MOV AL, 0
	MOV [ACTUALCOLORBYTE], AL

	;GET HANDLES
	PUSH -10
	CALL GetStdHandle
	MOV HANDLEIN, EAX

	PUSH -11
	CALL GetStdHandle
	MOV HANDLEOUT, EAX

	MOV ECX, 05H
	PUSH ECX
	PUSH HANDLEIN
	CALL SetConsoleMode

	;WRITE MSG
	LEA ECX, [MSG]
	LEA EDX, [NOMEMORYLEAKORELSE]
	PUSH 0
	PUSH EDX
	PUSH MSGLEN
	PUSH ECX
	PUSH HANDLEOUT
	CALL WriteConsoleA
	JMP WAITKEY

START ENDP

WAITKEY PROC
	;CHANGE TEXT COLOUR AND REPRINT
	MOV AL, ACTUALCOLORBYTE
	INC AL
	MOV [ACTUALCOLORBYTE], AL
	CALL BYTETONUM
	;REPRINT
	LEA ECX, [MSG]
	LEA EDX, [NOMEMORYLEAKORELSE]
	PUSH 0
	PUSH EDX
	PUSH MSGLEN
	PUSH ECX
	PUSH HANDLEOUT
	CALL WriteConsoleA

	;CHECK EVENTS
	LEA ECX, [NOMEMORYLEAKORELSE]
	PUSH ECX
	PUSH HANDLEIN
	CALL GetNumberOfConsoleInputEvents
	MOV ECX, NOMEMORYLEAKORELSE
	CMP ECX, 00H
	JE WAITKEY

	;READ EVENTS
	LEA EBX, [BUFFER]
	LEA ECX, [NOMEMORYLEAKORELSE]
	PUSH ECX
	PUSH 1
	PUSH EBX
	PUSH HANDLEIN
	CALL ReadConsoleInputA

	;SANITY CHECK
	CMP NOMEMORYLEAKORELSE, 00H
	JE WAITKEY

	;CHECK IF KEYBOARD EVENT
	MOV CL, BUFFER
	CMP CL, 01H ;KEY_EVENT_RECORD
	JE ENDING
	JMP START
ENDING:
	RET
WAITKEY ENDP

BYTETONUM PROC
	;AL CONTAINS BYTE NUMBER
	MOV AH, 0       ; CLEAR HIGH BYTE OF CX
	MOV BL, 10      ; DIVISOR
	
	;GET UNITS
	DIV BL
	ADD AH, '0'
	MOV [COLORBYTE+3], AH
	
	;GET TENS
	MOV AH, 0
	DIV BL
	ADD AH, '0'
	MOV [COLORBYTE+2], AH
	
	;GET HUNDREDS
	ADD AL, '0'
	MOV [COLORBYTE+1], AL

	;ADD LEADING 0 FOR COMPATABILITY WITH REGISTER THINGY
	MOV [COLORBYTE], '0'
	RET
BYTETONUM ENDP
END